# Generated by Django 5.0.4 on 2024-04-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelancer_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerEmailVerifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('user_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer_users.freelanceruser')),
            ],
        ),
    ]
